### ISSUE TITLE
With iOS 14 images, `--objc -U -vvv` terminates with exception rather than dumping class info

### ISSUE THREAD

**Issue by MLKrisJohnson** [DerekSelander/dsdump#13]
I've tried using `dsdump` to dump class information for executables on the iOS 14 Developer Disk Image included with Xcode 12, but attempts to do so result in a crash.

The Developer Disk Image can be found at `/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/14.0/DeveloperDiskImage.dmg` after installing the Xcode 12 beta. Double-click it to mount it.

Then, run one of these commands:

```
dsdump --objc --arch arm64 -U -vvv /Volumes/DeveloperDiskImage/usr/libexec/testmanagerd
dsdump --objc --arch arm64 -U -vvv /Volumes/DeveloperDiskImage/Library/Frameworks/XCTest.framework/XCTest
```

dsdump will be able to dump some information, but eventually terminates with messages like this:

```
0x0010006f0c8 XCSynthesizedEventRecord : NSObject <NSSecureCoding>
  // class methods
WARNING: couldn't find address 0x11c560002f328 (0x4560002f328) in binary!
2020-06-26 15:59:44.985 dsdump[37156:937781] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSString stringWithUTF8String:]: NULL cString'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff33aadbe7 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6cde55bf objc_exception_throw + 48
	2   Foundation                          0x00007fff36130af9 +[NSString stringWithUTF8String:] + 174
	3   dsdump                              0x000000010000ca83 _Z21dumpObjectiveCMethodsP11method_listPKcbbS2_ + 907
	4   dsdump                              0x000000010000fe53 -[XRMachOLibrary(ObjectiveC) dumpObjectiveCClasses] + 4212
	5   dsdump                              0x0000000100011028 -[XRMachOLibrary(SymbolDumper) dumpSymbols] + 127
	6   dsdump                              0x0000000100017f3a main + 1350
	7   libdyld.dylib                       0x00007fff6df8ccc9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    37156 abort      ~/Downloads/dsdump --objc -aarm64 -U -vvv 
```

I suspect this is related to this item in the Xcode 12 release notes:

- When the deployment target is iOS 14 or higher, the linker now converts Objective-C method lists into a new, smaller, read-only relative methods list in __TEXT. These binaries will not work on older versions of iOS or iPadOS. (56880461)

(from <https://developer.apple.com/documentation/xcode-release-notes/xcode-12-beta-release-notes>)

**Comment by blacktop** [comment]
@DerekSelander this is going to mess you up - https://developer.apple.com/videos/play/wwdc2020/10163/

**Comment by DerekSelander** [comment]
@MLKrisJohnson Added a patch.  Haven't thoroughly tested, so would appreciate you pinging me if something else pops up.  

Only went after the developer disk image which seemed to work ok..


```
find /Volumes/DeveloperDiskImage -type f -perm +111 -exec bash -c 'if !  dsdump -a arm64 -cov "{}" 1>/dev/null; then echo "{}"; fi ' \;
```

I'd keep an eye out for anything breaking on the iOS IPSW.  I am aware of how broken ARM64e is, this only addresses ARM64 for now
