### ISSUE TITLE
sha256 mentioned is wrong

### ISSUE THREAD

**Issue by jayahariv** [DerekSelander/dsdump#18]
I downloaded the `dsdump_compiled.zip` from the location, but the SHA seems to be different than mentioned in the `README.md`. 

Looks like the binary in this commit, https://github.com/DerekSelander/dsdump/commit/1a8857e447d1f2e683c4a6b376ba5918cdd419ee was overridden by a later commit https://github.com/DerekSelander/dsdump/commit/6770b4a8058d503e2b987f994c7eba655bce0125, but forget to update the SHA in README?

README says: `83eebd025b43b58a486235e1bec70a3239995be409605e3ff19bdae07adff917`
What I got: `3e8c2ff61f0bebdbc8c542605b8bfa69c96d14e1722ae46db8afd6c50cba5302`

```
/tmp 21:34:18 $ shasum -a 256 ~/Downloads/dsdump_compiled.zip 
3e8c2ff61f0bebdbc8c542605b8bfa69c96d14e1722ae46db8afd6c50cba5302
``

**Comment by DerekSelander** [comment]
Thanks, should be resolved.
