### ISSUE TITLE
Finding ASLR shift

### ISSUE THREAD

**Issue by localacct** [DerekSelander/dsdump#19]
Hi

Sorry, I was trying to ask a question but could not find an option to ask questions, so I raise an issue instead. I managed to write a simple program that can read the data structures of a mach o binary file by following your article on dsdump.

Using those details I got, is it possible to calculate the ASLR shift programmatically so that by adding that value to a function's address before ASLR, I can calculate where the function is in memory.

**Comment by DerekSelander** [comment]
Yes it is possible, but depends if you are in the process or another process inspecting that process.  If you are in process, check out the mach-o/dyld.h header file.  If you are out of process, check out the `task_info`/`TASK_DYLD_INFO` APIs. Note Apple has clamped down on this APIs to make it harder to inspect their code on iOS

**Comment by DerekSelander** [comment]
And yes, once you have the ASLR shift, you can infer the loaded mach-o at runtime
