### ISSUE TITLE
Assertion failed: Demangle.h line 217

### ISSUE THREAD

**Issue by xhruso00** [DerekSelander/dsdump#3]
Assertion failed: (getNumChildren() > index), function getChild, file /Users/lolgrep/code/swift-source/swift/include/swift/Demangling/Demangle.h, line 217.
Abort trap: 6

Trying to dissasemble:
https://www.icloud.com/iclouddrive/0Yd4RMA1vqAATc1EBAFZn2D6w#BarcodeScanner

**Comment by DerekSelander** [comment]
Hey @xhruso00, got the image and can replicate, feel free to take the link down.  I'll look into this over the week

**Comment by DerekSelander** [comment]
@xhruso00, grab beta-5 and see if that resolves it

**Comment by xhruso00** [comment]
@DerekSelander Yes, it works.
