### ISSUE TITLE
Unmatched brackets for empty classes?

### ISSUE THREAD

**Issue by saagarjha** [DerekSelander/dsdump#9]
Classes with no members are listed with empty brackets:

https://github.com/DerekSelander/dsdump/blob/9ca7faaa9665a1691e2baa8df6ec9c69377d6b56/dsdump/XRMachOLibrary%2BSwift.mm#L356

Is this intentional?

**Comment by DerekSelander** [comment]
Yeah, it's on purpose, but open to change it
